# Generated by Django 5.2.6 on 2025-09-27 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_supplier_purchaseinvoice_purchaseinvoiceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название причины')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Причина расхода',
                'verbose_name_plural': 'Причины расхода',
            },
        ),
        migrations.CreateModel(
            name='ExpenseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер накладной')),
                ('expense_date', models.DateField(verbose_name='Дата расхода')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=10, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.expensereason', verbose_name='Причина расхода')),
            ],
            options={
                'verbose_name': 'Накладная расхода',
                'verbose_name_plural': 'Накладные расхода',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Общая стоимость')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.expenseinvoice', verbose_name='Накладная')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка накладной расхода',
                'verbose_name_plural': 'Строки накладной расхода',
                'unique_together': {('invoice', 'product')},
            },
        ),
    ]
