# Generated by Django 5.0.7 on 2025-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_supplier_purchaseinvoice_purchaseinvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('кг', 'Килограммы'), ('м', 'Метры')], default='шт', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
