# Generated by Django 5.0.7 on 2025-09-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('manager', 'Менеджер'), ('viewer', 'Наблюдатель')], default='manager', max_length=20, verbose_name='Role'),
        ),
    ]
